Meloht.Quartz.WebManage/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Meloht.Quartz.JobCore;
using Meloht.Quartz.JobCore.Model;
using Meloht.Quartz.JobCore.Xml;
using Meloht.Quartz.WebManage.Common;
using Meloht.Quartz.WebManage.Models;
using Microsoft.AspNetCore.Mvc;
using Quartz;

namespace Meloht.Quartz.WebManage.Controllers
{
    public class JobController : Controller
    {
        private JobManger _job = new JobManger();
        public IActionResult JobListIndex()
        {
            return View();
        }

        public IActionResult GetCreateJobView()
        {
            return PartialView("JobCreateView");
        }

        public IActionResult GetUpdateJobView(string jobName, string group)
        {
            UpdateJobModel model = new UpdateJobModel();
            model.JobName = jobName;
            model.JobGroupValue = group;

            var data = XmlJobManage.GetJobDataByKey(new JobKey(jobName, group));
            if (data != null)
            {
                model.CronExpression = data.CronExpression;
                model.CallbackUrl = data.CallbackUrl;

            }

            return PartialView("UpdateJobView", model);
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



        [HttpPost]
        public JsonResult GetJobList(JobQueryModel model)
        {
            if (string.IsNullOrEmpty(model.JobName))
            {
                model.JobName = string.Empty;
            }

            var data = _job.GetJobList();
            var tdata = data.Where(p => p.JobName.Contains(model.JobName)).OrderBy(p => p.JobName).ToList();
            int total = tdata.Count;
            var list = tdata.Skip(model.Offset).Take(model.Limit).ToList(); ;
            return Json(new { total = total, rows = list });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult RunAtOnce(string jobName, string groupName)
        {
            bool bl = _job.RunAtOnce(jobName, groupName);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "运行成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "运行失败");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult CreateJob(JobHttpModel model)
        {
            if (!ModelState.IsValid)
            {
                return BaseJson(MsgCode.Failed, "数据验证失败");
            }

            JobParamHttpModel jobParam = new JobParamHttpModel();
            jobParam.JobName = model.JobName;
            jobParam.CronExpression = model.CronExpression;
            jobParam.CallbackUrl = model.CallbackUrl;
            jobParam.CallbackParams = GetParaDict(model.CallbackParams);

            bool bl = _job.AddHttpJob(jobParam);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "创建成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "创建失败");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult PauseJob(string jobName,string groupName)
        {

            bool bl = _job.PauseJob(jobName, groupName);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "暂停成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "暂停失败");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ResumeJob(string jobName, string groupName)
        {
            bool bl = _job.ResumeJob(jobName, groupName);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "恢复成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "恢复失败");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult DeleteJob(string jobName,string groupName)
        {
            var model = JobUtils.GetJobParamBase(jobName, groupName);

            bool bl = _job.DeleteJob(model);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "删除成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "删除失败");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult ModifyJob(UpdateJobModel model)
        {
            JobParamHttpModel jobParam = new JobParamHttpModel();
            jobParam.JobName = model.JobName;
            jobParam.CronExpression = model.CronExpression;
            jobParam.CallbackUrl = model.CallbackUrl;
            jobParam.CallbackParams = GetParaDict(model.CallbackParams);

            bool bl = _job.UpdateHttpJob(jobParam);
            if (bl)
            {
                return BaseJson(MsgCode.Success, "修改成功");
            }
            else
            {
                return BaseJson(MsgCode.Failed, "修改失败");
            }
        }

        [HttpGet]
        public JsonResult GetJobParaList(string jobName, string groupName)
        {
            var data = _job.GetJobParaList(jobName, groupName);
            return Json(data);

        }

        #region private

        private Dictionary<string, string> GetParaDict(string json)
        {
            Dictionary<string, string> dict = new Dictionary<string, string>();
            if (string.IsNullOrEmpty(json))
            {
                return dict;
            }

            var para = JobUtils.ToObject<List<KeyValueModel>>(json);
            if (para != null)
            {
                foreach (var item in para)
                {
                    if (!dict.ContainsKey(item.key))
                    {
                        dict.Add(item.key, item.value);
                    }
                }
            }
            return dict;
        }


        private JsonResult BaseJson(MsgCode code, string msg, object data = null)
        {
            object model = null;

            if (code == MsgCode.None)
            {
                model = data;
            }
            else
            {
                if (data != null)
                {
                    model = new { status = (int)code, msg = msg, data = data };
                }
                else
                {
                    model = new { status = (int)code, msg = msg };
                }
            }
            JsonResult json = new JsonResult(model);

            return json;
        }
        #endregion
    }
}

Meloht.Quartz.WebManage/Controllers/JobLogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using log4net;
using Meloht.Quartz.JobCore.Log;
using Meloht.Quartz.WebManage.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Meloht.Quartz.WebManage.Controllers
{
    public class JobLogController : Controller
    {
        private ILog _logger = LogManager.GetLogger(Log4NetHelper.Instance.RepositoryName, typeof(JobLogController));
        /// <summary>
        /// 运行日志
        /// </summary>
        /// <returns></returns>
        public IActionResult JobWorkLogList()
        {
            return View();
        }

        public IActionResult JobErrorLogList()
        {
            return View();
        }

        public IActionResult JobAppLogList()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetRunLogList(LogQueryModel model)
        {
            QueryParamModel query = GetQueryModel(model);

            var list = LogUtil.GetRunLogListPage(query);

            return Json(new { total = list.Total, rows = list.Rows });
        }

        [HttpPost]
        public JsonResult GetErrLogList(LogQueryModel model)
        {
            QueryParamModel query = GetQueryModel(model);

            var list = LogUtil.GetErrLogListPage(query);
            return Json(new { total = list.Total, rows = list.Rows });
        }

        [HttpPost]
        public JsonResult GetAppLogList(LogQueryModel model)
        {
            QueryParamModel query = GetQueryModel(model);
            var list = LogUtil.GetListPage(query);
            return Json(new { total = list.Total, rows = list.Rows });
        }
        [HttpGet]
        public void DownloadLog(string file)
        {
            try
            {
                string path = Log4NetHelper.Instance.GetFilePath(file);
                if (!System.IO.File.Exists(path))
                {
                    return;
                }

                Response.Clear();
                FileInfo fileInfo = new FileInfo(path);

                string ua = Request.Headers["UserAgent"];
                if (ua != null && ua.ToLower().IndexOf("firefox") > -1)
                {
                    Response.Headers.Add("Content-Disposition", "attachment;filename*=utf-8'zh_cn'" + HttpUtility.UrlEncode(file, System.Text.Encoding.UTF8));

                }
                else
                {
                    Response.Headers.Add("Content-Disposition", "attachment; filename=" + HttpUtility.UrlEncode(file, System.Text.Encoding.UTF8));
                }
                HttpContext.Response.Headers.Add("Content-Length", fileInfo.Length.ToString());
                HttpContext.Response.Headers.Add("Content-Transfer-Encoding", "binary");

                Response.ContentType = "application/octet-stream;charset=UTF-8";

                HttpContext.Response.SendFileAsync(path).GetAwaiter().GetResult();

            }
            catch (Exception e)
            {
                _logger.Error(e);
            }
        }

        private QueryParamModel GetQueryModel(LogQueryModel model)
        {
            QueryParamModel data = new QueryParamModel();

            data.KeyWord = model.KeyWord ?? "";
            data.BeginDate = LogUtil.GetDateFormName(model.BeginDate, DateTime.MinValue);
            data.EndDate = LogUtil.GetDateFormName(model.EndDate, DateTime.MaxValue);

            data.Limit = model.Limit;
            data.Offset = model.Offset;

            return data;
        }

    }
}

Meloht.Quartz.WebManage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - 后台任务管理</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-table/bootstrap-table.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker3.css" />
    </environment>
    <environment exclude="Development">


        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-table/bootstrap-table.min.css" />
        <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker3.min.css" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Job" asp-action="JobListIndex" class="navbar-brand">后台任务管理</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Job" asp-action="JobListIndex">任务列表</a></li>
                    <li><a asp-area="" asp-controller="JobLog" asp-action="JobWorkLogList">任务运行日志</a></li>
                    <li><a asp-area="" asp-controller="JobLog" asp-action="JobErrorLogList">任务异常日志</a></li>
                    <li><a asp-area="" asp-controller="JobLog" asp-action="JobAppLogList">应用程序异常日志</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-fluid body-content">
        @RenderBody()
        <hr />
        @*<footer>
                <p>&copy; 2018 - </p>
            </footer>*@
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery.validate.unobtrusive.bootstrap/jquery.validate.unobtrusive.bootstrap.js"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap-table/bootstrap-table.js"></script>
        <script src="~/lib/bootstrap-table/locale/bootstrap-table-zh-CN.js"></script>
        <script src="~/lib/layer/layer.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
        <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
        <script src="~/js/msgbox.js"></script>
        <script src="~/js/appcomm.js"></script>
    </environment>
    <environment exclude="Development">

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>

        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/jquery.validate.unobtrusive.bootstrap/jquery.validate.unobtrusive.bootstrap.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>

        <script src="~/lib/bootstrap-table/bootstrap-table.min.js"></script>
        <script src="~/lib/bootstrap-table/locale/bootstrap-table-zh-CN.min.js"></script>
        <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
        <script src="~/lib/bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js"></script>
        <script src="~/lib/layer/layer.js"></script>

        <script src="~/js/msgbox.js"></script>
        <script src="~/js/appcomm.js"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>